image:
  repo: 672188301118.dkr.ecr.eu-west-1.amazonaws.com/zesty-k8s/data-store
  tag: 1.50.5
ingress:
  ClassName: internal
  host: k8s-data-store.staging.zesty.co
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi
logLevel: INFO
env:
  - name: API_STAGE
    value: staging
  - name: AWS_DEFAULT_REGION
    value: us-west-2
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: OTEL_TRACES_EXPORTER
    value: otlp_proto_grpc
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://$(HOST_IP):4317"
  - name: OTEL_PYTHON_FASTAPI_EXCLUDED_URLS
    value: "health,metrics"
environment:
  apiStage: staging
  region: us-west-2
hpa:
  min: 2
  max: 4
pdb:
  maxUnavailable: 1
clustersRefreshSQS: /staging/zesty-k8s/data-store/refresh_clusters_worker/sqs
generateRecommendationsSQS: /staging/zesty-k8s/data-store/k8s_recommendations/sqs
slackBotToken: /staging/notifications/slack-bot-token
slackChannelName: k8s-notifications-staging
buckets:
  agentPayload: external-staging.zesty.co
  clusterState: zesty-cluster-state-staging
  bronze_pricing: zesty-pricing-bronze-staging
  silver_pricing: zesty-pricing-silver-staging
pricing_files:
  spot_file_key: aws_spot_data/LATEST/aws_spot_data.parquet
  od_file_key: ec2_ondemand/aws_pricing_od_silver.parquet
dynamodb:
  accounts: staging-accounts
  organizations: staging-organizations
  resellers: staging-resellers
  users: staging-users
api:
  apiGateway:
    stage: staging
    region: us-west-2
    path: ""
  externalSecret:
    appConfig:
      audienceAuth0: /staging/common/auth0-audience
      domainAuth0: /staging/common/auth0-domain
      auth0Cred: staging/common/auth0/cred
      audienceSystemAuth0: /staging/common/auth0-audience-system
      databaseCredentials: staging/zesty-k8s/data-store/cred
      databaseDetails: staging/zesty-k8s/data-store/database
      elasticDetails: staging/spots/elastic-credentials
cronjob:
  externalSecret:
    appConfig:
      audienceAuth0: /staging/common/auth0-audience
      domainAuth0: /staging/common/auth0-domain
      audienceSystemAuth0: /staging/common/auth0-audience-system
      auth0Cred: staging/common/auth0/cred
      databaseCredentials: staging/zesty-k8s/data-store/cred
      databaseDetails: staging/zesty-k8s/data-store/database
      recommendationServiceSQS: /staging/incubations/recommendations-resolver/sqs
  schedule: 0 17 * * *
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
worker:
  awsRegion: us-west-2
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      audienceAuth0: /staging/common/auth0-audience
      domainAuth0: /staging/common/auth0-domain
      audienceSystemAuth0: /staging/common/auth0-audience-system
      auth0Cred: staging/common/auth0/cred
      sqsQueueURL: /staging/zesty-k8s/data-store/sqs
      databaseCredentials: staging/zesty-k8s/data-store/cred
      databaseDetails: staging/zesty-k8s/data-store/database
      elasticDetails: staging/spots/elastic-credentials
      publicRedis: staging/data-engineering/serverless-backend/redis-public-cache
      privateRedis: staging/data-engineering/serverless-backend/redis-cache
      auditLogSQS: /staging/audit-log/sqs
recommendationsCronJob:
  schedule: 0 * * * *
refreshClustersWorker:
  awsRegion: us-west-2
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      databaseCredentials: staging/zesty-k8s/data-store/cred
      databaseDetails: staging/zesty-k8s/data-store/database
