image:
  repo: 672188301118.dkr.ecr.eu-west-1.amazonaws.com/zesty-k8s/data-store
  tag: 1.38.3
ingress:
  ClassName: external
  host: k8s-data-store.zesty.co
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
logLevel: INFO
env:
  - name: API_STAGE
    value: prod
  - name: AWS_DEFAULT_REGION
    value: eu-west-1
environment:
  apiStage: prod
  region: eu-west-1
hpa:
  min: 2
  max: 10
pdb:
  maxUnavailable: 1
clustersRefreshSQS: /production/zesty-k8s/data-store/refresh_clusters_worker/sqs
slackBotToken: /prod/notifications/slack-bot-token
slackChannelName: k8s-notifications-production
buckets:
  agentPayload: external.zesty.co
  clusterState: zesty-cluster-state
  bronze_pricing: zesty-pricing-bronze
  silver_pricing: zesty-pricing-silver
pricing_files:
  spot_file_key: aws_spot_data/LATEST/aws_spot_data.parquet
  od_file_key: ec2_ondemand/aws_pricing_od_silver.parquet
dynamodb:
  accounts: accounts
  organizations: organizations
  resellers: resellers
  users: users
api:
  apiGateway:
    stage: prod
    region: eu-east-1
    path: ""
  externalSecret:
    appConfig:
      audienceAuth0: /prod/common/auth0-audience
      domainAuth0: /prod/common/auth0-domain
      auth0Cred: production/common/auth0/cred
      audienceSystemAuth0: /prod/common/auth0-audience-system
      databaseCredentials: prod/zesty-k8s/data-store/cred
      databaseDetails: prod/zesty-k8s/data-store/database
      elasticDetails: production/zesty-k8s/elastic-credentials
cronjob:
  externalSecret:
    appConfig:
      audienceAuth0: /prod/common/auth0-audience
      domainAuth0: /prod/common/auth0-domain
      audienceSystemAuth0: /prod/common/auth0-audience-system
      auth0Cred: production/common/auth0/cred
      databaseCredentials: prod/zesty-k8s/data-store/cred
      databaseDetails: prod/zesty-k8s/data-store/database
      recommendationServiceSQS: /production/incubations/recommendations-resolver/sqs
  schedule: 0 17 * * *
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
worker:
  awsRegion: eu-west-1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      audienceAuth0: /prod/common/auth0-audience
      domainAuth0: /prod/common/auth0-domain
      audienceSystemAuth0: /prod/common/auth0-audience-system
      auth0Cred: production/common/auth0/cred
      sqsQueueURL: /production/zesty-k8s/data-store/sqs
      databaseCredentials: prod/zesty-k8s/data-store/cred
      databaseDetails: prod/zesty-k8s/data-store/database
      elasticDetails: production/zesty-k8s/elastic-credentials
      publicRedis: prod/data-engineering/serverless-backend/redis-public-cache
      privateRedis: prod/data-engineering/serverless-backend/redis-cache
refreshClustersWorker:
  awsRegion: eu-west-1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      databaseCredentials: prod/zesty-k8s/data-store/cred
      databaseDetails: prod/zesty-k8s/data-store/database
