apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "zesty-k8s.role" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - "{{ .Values.insights.secret }}"
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch"]
