apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.admission.insights.service }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
  ports:
    - name: grpc
      {{- if .Values.admission.enabled }}
      port: {{ .Values.admission.grpc.server.port }}
      {{- end }}
      targetPort: grpc
      protocol: TCP
    - name: healthz
      port: {{ .Values.health.port }}
      targetPort: healthz
      protocol: TCP
  type: ClusterIP
