{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "zesty-k8s.svc" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
  ports:
    - name: grpc
      port: {{ .Values.admissionController.grpc.server.port }}
      targetPort: grpc
      protocol: TCP
    - name: healthz
      port: {{ .Values.health.port }}
      targetPort: healthz
      protocol: TCP
  type: ClusterIP
{{- end }}
