apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "zesty-k8s.fullname" . }}-updater-app-config"
data:
  app-config.yaml: |
    release_name: {{ .Release.Name }}
    helm:
      repo_name: {{ .Values.autoUpdate.helm.repoName }}
      repo_url: {{ .Values.autoUpdate.helm.repoURL }}
      chart_name: {{ .Values.autoUpdate.helm.chartName }}
    secret_substring: {{ .Values.autoUpdate.helm.secretSubstring }}
