{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "zesty-admission-controller.configMap" . }}
data:
  AGENT_HOST:  "{{ include "zesty-k8s.svc" . }}"
  {{- if hasKey .Values.admissionController "grpc" }}
  AGENT_PORT: "{{ .Values.admissionController.grpc.server.port }}"
  GRPC: "{{ .Values.admissionController.grpc.port }}"
  {{- else if and (hasKey .Values "grpc") (eq .Values.grpc.enabled true) }}
  AGENT_PORT: "{{ .Values.grpc.server.port }}"
  GRPC: "{{ .Values.grpc.client.port }}"
  {{- end }}
  SECRET: {{ include "zesty-k8s.secret" . }}
  LOG_LEVEL: "{{ .Values.log.level }}"
  LOG_REMOTE: "{{ .Values.log.remote }}"
{{- end }}
