apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "zesty-admission-controller.role" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-admission-controller.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-admission-controller.fullname" . }}"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - "{{ include "zesty-k8s.secret" . }}"
    verbs:
      - get