{{- if .Values.admissionController.enabled }}
{{- $ca := genCA (printf "*.%s.svc" (include "zesty-admission-controller.namespace" .)) 1024 -}}
{{- $svcName := (printf "%s.%s.svc" (include "zesty-admission-controller.serviceName" .) (include "zesty-admission-controller.namespace" .)) -}}
{{- $cert := genSignedCert $svcName nil (list $svcName) 1024 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zesty-admission-controller.serviceName" . }}.{{ template "zesty-admission-controller.namespace" . }}.svc.zesty-admission-controller-tls-ca
  namespace: {{ template "zesty-admission-controller.namespace" . }}
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/tls
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zesty-admission-controller.serviceName" . }}.{{ template "zesty-admission-controller.namespace" . }}.svc.zesty-admission-controller-tls-pair
  namespace: {{ template "zesty-admission-controller.namespace" . }}
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "zesty-admission-controller.fullname" . }}-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "5"
webhooks:
- name: nodepool.karpenter.sh
  clientConfig:
    service:
      name: {{ include "zesty-admission-controller.serviceName" . }}
      namespace: {{ template "zesty-admission-controller.namespace" . }}
      path: /mutate
    caBundle: {{ $cert.Cert | b64enc }}
  rules:
  - operations: ["CREATE", "UPDATE", "CONNECT"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  - operations: ["CREATE", "UPDATE", "CONNECT"]
    apiGroups: ["karpenter.sh"]
    apiVersions: ["v1beta1"]
    resources: ["nodepools"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Ignore
{{- end }}