{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "zesty-admission-controller.serviceName" . }}
spec:
  selector:
    app: {{ include "zesty-admission-controller.fullname" . }}
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: grpc
    {{- if and (hasKey .Values "grpc") (eq .Values.grpc.enabled true) }}
    port: {{ .Values.grpc.client.port }}
    targetPort: {{ .Values.grpc.client.port }}
    {{- else if hasKey .Values.admissionController "grpc" }}
    port: {{ .Values.admissionController.grpc.port }}
    targetPort: {{ .Values.admissionController.grpc.port }}
    {{- end }}
  type: ClusterIP
{{- end }}
