{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zesty-admission-controller.sa" . }}
  namespace: {{ template "zesty-admission-controller.namespace" . }}
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}
{{- end }}