image:
  repo: 672188301118.dkr.ecr.eu-west-1.amazonaws.com/k8s/validator
  tag: 1.19.14
env:
  - name: API_STAGE
    value: "prod"
  - name: AWS_DEFAULT_REGION
    value: "eu-west-1"
slackBotToken: /prod/notifications/slack-bot-token
slackChannelName: "k8s-notifications-production"
buckets:
  agentPayload: "external.zesty.co"
  clusterState: "zesty-cluster-state"
dynamodb:
  accounts: accounts
  organizations: organizations
  resellers: resellers
  users: users
worker:
  awsRegion: "eu-west-1"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      audienceAuth0: "/prod/common/auth0-audience"
      domainAuth0: "/prod/common/auth0-domain"
      audienceSystemAuth0: "/prod/common/auth0-audience-system"
      auth0Cred: "production/common/auth0/cred"
      sqsQueueURL: "/prod/zesty-k8s/file-validation/sqs"
      dataStoreSNSArn: "/prod/zesty-k8s/data-store/sns"
      publicRedis: "prod/data-engineering/serverless-backend/redis-public-cache"
      privateRedis: "prod/data-engineering/serverless-backend/redis-cache"
  restartPolicy: Never
  backoffLimit: 3
