# -- (string) Override the name of the chart
nameOverride: ~
# -- (string) Override the expanded name of the chart
fullnameOverride: ~
# -- (string) Override the namespace the chart deploys to
namespaceOverride: ~
# -- (int) Set grpc port
grpc:
  port: 50051
# -- ServiceAccount annotations
serviceAccount:
  annotations:
# -- Deployment Node Selector
nodeSelector:
  team: zesty-k8s
  karpenter.sh/capacity-type: on-demand
# -- Deployment Tolerations
tolerations:
  - effect: NoSchedule
    key: team
    operator: Equal
    value: zesty-k8s
