apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.name }}-recommendation-cronjob"
  labels: {{- include "labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ .Values.name }}-recommendation-scheduler"
          labels:
            app: {{ .Values.name }}
        spec:
          serviceAccountName: {{ .Values.name }}
          tolerations:
            - effect: NoSchedule
              key: team
              operator: Equal
              value: zesty-k8s
          nodeSelector:
            team: "zesty-k8s"
          containers:
          - name: "{{ .Values.name }}-recommendation-scheduler"
            image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            env: {{ toYaml .Values.env | nindent 12 }}
            volumeMounts:
            - mountPath: /app/app-config.yaml
              name: app-config
              subPath: app-config.yaml
            command: ["opentelemetry-instrument", "--traces_exporter","otlp","--metrics_exporter","none","--service_name", "k8s-data-store-recommendations-scheduler", "python3", "/app/src/cron_jobs/generate_recommendations.py"]
            resources:
            {{- toYaml .Values.resources | nindent 16 }}
          volumes:
          - name: app-config
            secret:
              secretName: "{{ .Values.name }}-cronjob-app-config"
          restartPolicy: "Never"

