apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.name }}"
  annotations:
        eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.awsRoleArn }}"
{{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}