apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zesty-admission-controller.cr" . }}
  namespace: {{ template "zesty-admission-controller.namespace" . }}
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
rules:
  - apiGroups:
      - "karpenter.sh"
    resources:
      - nodepools
      - nodeclaims
    verbs:
      - get
      - list
