apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "zesty-admission-controller.configMap" . }}
data:
  AGENT_HOST: "zesty-k8s-helm-svc"
  AGENT_PORT: "50052"
  GRPC: "{{ .Values.grpc.port }}"
