apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ include "zesty-admission-controller.configMap" . }}
data:
  REDIS_ADDR: "{{ .Release.Name }}-redis-ha-haproxy:{{ .Values.externalRedis.port }}"
