apiVersion: v1
kind: Secret
metadata:
  name: zesty-admission-controller-redis
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
  {{- with .Values.externalRedis.secretAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.externalRedis.username }}
  redis-username: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.externalRedis.password }}
  redis-password: {{ . | b64enc }}
  {{- end }}
