apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "zesty-admission-controller.serviceName" . }}
  namespace: {{ template "zesty-admission-controller.namespace" . }}
spec:
  selector:
    app: {{ include "zesty-admission-controller.fullname" . }}
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP
