apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ include "zesty-admission-controller.fullname" . }}
  namespace: {{ template "zesty-admission-controller.namespace" . }}
  labels:
    app: {{ include "zesty-admission-controller.fullname" . }}
spec:
  serviceName: {{ include "zesty-admission-controller.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "zesty-admission-controller.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "zesty-admission-controller.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 443
            protocol: TCP
          volumeMounts:
            - mountPath: "/etc/webhook/tls"
              name: webhook-tls
              readOnly: true
        - name: {{ .Chart.Name }}-redis
          image: "{{ .Values.image.redis }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          command: ["sh", "-c"]
          args:
            - |
              if [ "$(hostname)" = "{{ include "zesty-admission-controller.fullname" . }}-0" ]; then
                redis-server;
              else
                redis-server --replicaof {{ include "zesty-admission-controller.serviceName" . }} 6379;
              fi
          envFrom:
            - configMapRef:
                name: {{ include "zesty-admission-controller.configMap" . }}
      volumes:
        - name: webhook-tls
          secret:
            secretName: {{ template "zesty-admission-controller.serviceName" . }}.{{ template "zesty-admission-controller.namespace" . }}.svc.zesty-admission-controller-tls-pair
