apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels: {{- include "labels" . | nindent 4 }}
spec:
  selector: {{- include "labels" . | nindent 4 }}
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
