namespace: "zesty-k8s"

zestyk8s:
  nodeSelector:
    team: "zesty-k8s"
    karpenter.sh/capacity-type: on-demand
  tolerations:
    - effect: NoSchedule
      key: team
      operator: Equal
      value: zesty-k8s
