zestyk8s:
  prometheus:
    url: http://prometheus-stack-prometheus.monitoring:9090/
  awsAthena:
    enabled: true
    athenaProjectID: "672188301118"
    athenaBucketName: s3://zesty-k8s-athena-result/zesty
    athenaRegion: eu-west-1
    athenaDatabase: athenacurcfn_zesty_k8s_export
    athenaTable: zesty_k8s_export
    athenaWorkgroup: primary
    athenaCatalog: AwsDataCatalog
  s3override:
    enabled: true
    bucket: "external.zesty.co"
    region: "eu-west-1"
  orgID: "3863721556980"
  namespace: "zesty-k8s"
  grpc:
    enabled: true
    client:
      endpoint: zesty-admission-webhook-zesty-admission-controller-svc
  fullnameOverride: "prod-zesty-k8s"
  persistence:
    spec:
      storageClassName: "ebs-sc-delete"
      accessModes:
        - ReadWriteOnce
  config:
    manager:
      enable: true
  image:
    repository: "672188301118.dkr.ecr.eu-west-1.amazonaws.com/zesty-k8s/agent"
    tag: "1.32.2"
externalSecret:
  agentCreds:
    key: "prod/zesty-k8s/encrypted-creds"
