apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.name }}-worker-keda"
spec:
  secretStoreRef:
    name: aws-parameter-store-secretstore
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.name }}-worker-keda"
    template:
      engineVersion: v2
      data:
        AWS_SQS_QUEUE_URL: "{{`{{ .queueURL }}`}}"
  data:
    - secretKey: queueURL
      remoteRef:
        key: "{{ .Values.clustersRefreshSQS}}"
