apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodepool-mapper.fullname" . }}
  labels:
    {{- include "nodepool-mapper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodepool-mapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodepool-mapper.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nodepool-mapper.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: {{ .Values.service.port }}
