apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.name }}-creds"
spec:
  secretStoreRef:
    name: aws-secret-manager-secretstore
    kind: ClusterSecretStore
  target:
    name: "zesty-k8s-agent-creds"
  data:
    - secretKey: encrypted_credentials
      remoteRef:
        key: "{{ .Values.externalSecret.agentCreds.key }}"
        property: encryptedCredentials
