apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zesty-agent.cr" . }}
  namespace: {{ template "zesty-agent.namespace" . }}
  labels:
    app: {{ include "zesty-agent.fullname" . }}
rules:
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
