image:
  repo: 672188301118.dkr.ecr.eu-west-1.amazonaws.com/spots/validation
  tag: 1.19.14
env:
  - name: API_STAGE
    value: "prod"
  - name: AWS_DEFAULT_REGION
    value: "eu-west-1"
worker:
  awsRegion: "eu-west-1"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  logLevel: INFO
  externalSecret:
    appConfig:
      audienceAuth0: "/prod/common/auth0-audience"
      domainAuth0: "/prod/common/auth0-domain"
      audienceSystemAuth0: "/prod/common/auth0-audience-system"
      auth0Cred: "production/common/auth0/cred"
      sqsQueueURL: "/production/zesty-k8s/file-validation/sqs"
      dataStoreSNSArn: "/production/zesty-k8s/data-store/sns"
  restartPolicy: Never
  backoffLimit: 3
