apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels: {{- include "labels" . | nindent 6 }}
