replicaCount: 1
image:
  repository: "473301030746.dkr.ecr.us-west-2.amazonaws.com/zesty-k8s/nodepool-mapper"
  pullPolicy: IfNotPresent
  tag: "1.0.1"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
